apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
type: Opaque
data:
  database_url: amRiYzpteXNxbDovL2hvc3Q6MzMwNjAvY2lwcmlhbi11cnN1bGVhbg==  #jdbc:mysql://host:33060/ciprian-ursulean
  database_name: bXlzcWw=  #mysql
  database_type: U1FM #SQL
