apiVersion: v1
kind: Pod
metadata:
  name: secret-printer-pod
spec:
  containers:
    - name: secret-data-printer
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "echo database_url: $(database_url_env), database_name: $(database_name_env), database_type: $(database_type_env)" ]
      env:
        - name: database_url_env
          valueFrom:
            secretKeyRef:
              name: secret-demo
              key: database_url
        - name: database_name_env
          valueFrom:
            secretKeyRef:
              name: secret-demo
              key: database_name
        - name: database_type_env
          valueFrom:
            secretKeyRef:
              name: secret-demo
              key: database_type
  restartPolicy: Never